# Generated by Django 5.2.5 on 2025-08-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_cuisine_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
